Added semantic cube
David-GaTre/Compilador-TUDI pull request #7
Opened 2022-10-13 06:14 UTC by David-GaTre

2022-10-13 21:54 UTC, Angel-AG requested changes

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +
Remover import y whitespace.

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +class sem_cube:
```suggestion
class SemanticCube:
```

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +    valid_ops = {
```suggestion
    valid_operations = {
```
O puede ser:
```suggestion
    valid_expressions= {
```

Elegir uno para que tenga consistencia con los métodos.

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +    def exp(self, left_ope:str, right_ope:str, operator:str):
```suggestion
    def create_operation(self, left_operand: str, right_operand: str, operator: str):
```

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +    def validate_exp(self, left_ope:str, right_ope:str, operator:str):
```suggestion
    def validate_operation(self, left_operand: str, right_operand: str, operator: str):
```

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +        if expression in self.valid_ops.keys():
```suggestion
        if expression in self.valid_ops:
```
Por default se checan las keys.

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +        return operator + ',' + left_ope + right_ope
¿Por qué decidiste poner una coma?

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +        expression = exp(left_ope, right_ope, operator)
Agregar el self.
```suggestion
        expression = self.exp(left_ope, right_ope, operator)
```

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +
No entiendo el punto de tener este diccionario. ¿Me explicas? O.o

Tener constantes me parece suficiente y mejor:
```
INT = 'int'
FLOAT = 'float'
. . .
```

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +        # Float - Float
Falta `Float - Int`.

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +        # Bool Bool
```suggestion
        # Bool - Bool
```

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +        'o,BF': data_types['bool'],
Cambiar todas las `BF` a `BB`.

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +        '*,BF': data_types['float'],
Me parece mejor que estas 3 sean `int`. Ya comenté en el doc para hacer el cambio ahí también.

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +            return "ERROR: Not valid operation"
No es necesario el `else`.

```suggestion
        return "ERROR: Not valid operation"
        
```

2022-10-13 21:54 UTC, Angel-AG commented on sem_cube.py
> +            return "ERROR: Not valid operation"
Todo esto también podría ser un one-liner, dejo a tu consideración.
```suggestion
        return self.valid_ops.get(expression, "ERROR: Not valid operation")
```

2022-10-13 23:15 UTC, David-GaTre commented on sem_cube.py
> +        return operator + ',' + left_ope + right_ope
Para que hubiera una separacion y no se vea tan feo pa nosotros

2022-10-13 23:23 UTC, David-GaTre commented on sem_cube.py
> +            return "ERROR: Not valid operation"
Mucha razon

2022-10-13 23:59 UTC, Angel-AG requested changes

2022-10-13 23:59 UTC, Angel-AG commented on sem_cube.py
> +
Aguas.

2022-10-13 23:59 UTC, Angel-AG commented on sem_cube.py
> +
Pero esto no se borró. (?)

2022-10-13 23:59 UTC, Angel-AG commented on sem_cube.py
> +    def create_operation(self, left_operand: str, right_operand: str, operator: str):
Se supone que si se escogía `valid_expressions` para el diccionario de arriba, entonces los métodos iban a llevar expression, en lugar de operations. Jaja

2022-10-15 04:04 UTC, Angel-AG approved these changes

2022-10-15 04:05 UTC, merged